steps:
- name: 'gcr.io/k8s-skaffold/pack'
  env:
  - 'GOOGLE_RUNTIME_VERSION=17'
  args: ['build', '--builder=gcr.io/buildpacks/builder:v1', '--publish', 'gcr.io/$PROJECT_ID/sso-app']
# Build the JAR file
- name: 'maven:3-openjdk-17'
  entrypoint: 'mvn'
  args: ['package', '-DskipTests']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/sso-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/sso-app']

# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'sso-app'
  - '--image'
  - 'gcr.io/chatgptdata-425219/sso-app'
  - '--region'
  - 'europe-north1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'

images:
- 'gcr.io/chatgptdata-425219/sso-app'
options:
  logging: GCS_ONLY
  logsBucket: 'gs://chatgptdata-425219_cloudbuild-logs'