steps:
  # Build the JAR file
  - name: 'maven:3-openjdk-17'
    entrypoint: 'mvn'
    args: ['package', '-DskipTests']
  
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sso-app', '.']

# Push the image to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/sso-app'
